const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('settings', {
  load: () => ipcRenderer.invoke('settings-load'),
  save: (value) => ipcRenderer.invoke('settings-save', value),
  testDeepSeek: () => ipcRenderer.invoke('test-deepseek'),
  testVision: () => ipcRenderer.invoke('test-vision'),
  openLogs: () => ipcRenderer.invoke('open-logs'),
  clearVisionCache: () => ipcRenderer.invoke('clear-vision-cache'),
  clearSecrets: () => ipcRenderer.invoke('clear-secrets'),
  usageSnapshot: () => ipcRenderer.invoke('usage-snapshot'),
  usageClear: () => ipcRenderer.invoke('usage-clear'),
  usageOpenBilling: () => ipcRenderer.invoke('usage-open-billing'),
  openUsage: () => ipcRenderer.invoke('open-usage-window'),
  agentLevels: () => ipcRenderer.invoke('agent-levels'),
  exportProfile: () => ipcRenderer.invoke('settings-export-profile'),
  importProfile: () => ipcRenderer.invoke('settings-import-profile'),
  exportData: () => ipcRenderer.invoke('settings-export-data'),
  openData: () => ipcRenderer.invoke('settings-open-data'),
  clearUsage: () => ipcRenderer.invoke('settings-clear-usage'),
  clearLogs: () => ipcRenderer.invoke('settings-clear-logs'),
  clearSessions: () => ipcRenderer.invoke('settings-clear-sessions'),
  clearHandoffHistory: () => ipcRenderer.invoke('settings-clear-handoff-history'),
  clearCache: () => ipcRenderer.invoke('settings-clear-cache'),
  close: () => ipcRenderer.invoke('settings-close'),
});
